### ISSUE TITLE
Folding code blocks

### ISSUE THREAD

**Issue by adamghowiba** [theoludwig/vscode-styled-jsx#139]
### Description
Similar to how Svelte's style tag CSS blocks allow folding and unfolding. With support for SCSS nested folding. 

### Describe the solution you'd like

Ability to click on the sidebar and fold or unfold a code block. 

### Describe alternatives you've considered

None

**Comment by Divlo** [comment]
Hey! :wave:

Thanks for your report!
Feel free to open PRs. :smile:
