### ISSUE TITLE
Warning for unused CSS

### ISSUE THREAD

**Issue by adamghowiba** [theoludwig/vscode-styled-jsx#140]
### Description

Ability to detect unused CSS classes. Similar to how Svelte offers a yellow warning above the code block. Allows an easy way to scan code and determine which CSS blocks are not being utilized. 

### Describe the solution you'd like
- Simple yellow floating message above the code block(s) that are unused.
- For users that may not prefer it, the ability to disable this option through configuration.

### Describe alternatives you've considered
Manually detecting unused CSS. I believe styled-jsx strips unused CSS, but it would still be a great feature to reduce lines and clean up large code bases.

**Comment by Divlo** [comment]
Hey! :wave:

Thanks for your report!
Feel free to open PRs. :smile:

**Comment by TechnoPvP** [comment]
@Divlo thanks for the quick response. I'm not familiar with VSCode extensions, but I'll give this feature request a short.

Would you be able to handle #139 since it's way beyond my scope of knowledge?

**Comment by Divlo** [comment]
Sorry, I don't have time/motivation to still develop for this extension, as I'm not using `styled-jsx` anymore.
But can still do the "strict minimum" by accepting PRs, reviewing them, and maybe release new version if needed. :smile:
